<?php

/**
 * Implements hook_menu().
 * 
 * @return string
 */
function password_policy_menu() {
  $items = array();
  
  $items['admin/config/people/password_policy'] = array(
    'title' => 'Password policies',
    'route_name' => 'password_policy.settings'
  );
  
  return $items;
}


/**
 * Implements hook_permission().
 */
function password_policy_permission() {
  return array(
    'administer password policies' => array(
      'title' => t('Administer policies'),
    ),
    'unblock expired accounts' => array(
      'title' => t('Unlock expired accounts'),
    ),
    'force password change' => array(
      'title' => t('Force password change'),
    ),
  );
}
